default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres          # Your PostgreSQL username
  password: Cwl123141!!    # The password you set during installation
  host: localhost

development:
  <<: *default
  database: postbox_development

test:
  <<: *default
  database: postbox_test

production:
  adapter: postgresql
  encoding: unicode
  database: postbox
  username: collinwilliamlewis@gmail.com
  password: Cwl123141!!
  host: localhost

