default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postbox_development
  username: postgres
  password: your_development_password
  host: localhost

test:
  <<: *default
  database: postbox_test
  username: postgres
  password: your_test_password
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
