default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTBOX_DATABASE_USERNAME'] %> # Replace with your username
  password: <%= ENV['POSTBOX_DATABASE_PASSWORD'] %> # Replace with your password
  host: <%= ENV['POSTBOX_DATABASE_HOST'] %>       # Replace with your database host

development:
  <<: *default
  database: postbox_development

test:
  <<: *default
  database: postbox_test

production:
  <<: *default
  database: postbox_production
  username: <%= ENV['POSTBOX_DATABASE_USERNAME'] %> # You might use different credentials
  password: <%= ENV['POSTBOX_DATABASE_PASSWORD'] %> # for production.
  host: <%= ENV['POSTBOX_DATABASE_HOST'] %>
